### ISSUE TITLE
Switch to the new depend mechanism

### ISSUE THREAD

**Issue by OndrejMarsalek** [cosmo-epfl/i-pi-dev#116]
All code should be converted to the new depend mechanism added in #55. This is best left for a time when there are no outstanding major merges.

**Comment by ceriottm** [comment]
Reviving this issue. We have merged the terser depend handling patch. We deprecate dset and dget and wait for some kind soul to go through the pain of refactoring most of the initializations.

**Comment by tomspur** [comment]
As this seems to have been stale lately, I revived it in #209 and removed `dset` there at least.
