### ISSUE TITLE
Python versions and .format call

### ISSUE THREAD

**Issue by mahrossi** [cosmo-epfl/i-pi-dev#132]
Dear all (perhaps mostly Ondrej who implemented the backup machinery?),

I'm trying to use i-pi in a HPC cluster where the python version is 2.6.9. I am getting:

"ValueError: zero length field name in format"

in many .format calls associated with open_backup and other similar calls in the backup routines. I looked up and passing indexes for the format field, or not passing, seems to depend highly on the python version (from a forum: "Python 2.6 and 3.0 require the field numbers. In Python 2.7 and later and 3.1 and later, they can be omitted."). How to best solve this? Do we need the format calls?

Cheers,

Mariana

**Comment by ceriottm** [comment]
Has this problem been fixed?
