### ISSUE TITLE
i-pi website 

### ISSUE THREAD

**Issue by grhawk** [cosmo-epfl/i-pi-dev#141]
Hello,

We have a new website... before making it public, it would be important to have the opinions of everyone... 

To see the website just go [here](https://epfl-cosmo.github.io/i-pi-dev/).
You can obviously modify the site as you please. The website is in the "gh-pages" branch. All the pages are in the "pages" directory (very original :) ) and they should be quite easy to understand and modify since it is all markdown. News&Events are in the _posts directory. There is just a dummy news that could be used as a template.

**Comment by mahrossi** [comment]
Hmm is it possible that there are some big files in gh-pages branch that
could make the pulling of the i-pi-dev repository a bit painful?

On Tue, Sep 6, 2016 at 4:32 PM, Riccardo Petraglia <notifications@github.com

**Comment by mahrossi** [comment]
I am correcting some typos and adding a few things, but would suggest changing the DNA in the bottle of the header picture for some other image that contains other types of molecules/materials and that highlights the "interface" nature of i-PI?

**Comment by grhawk** [comment]
I did that picture some time ago for a different reason... Changing the DNA could be possible... but would probably require a week full time... I will check for file dimension

**Comment by mahrossi** [comment]
The picture looks very nice! It is just that I don't see how it relates to i-PI :)

**Comment by ceriottm** [comment]
I agree that that image -- albeit beautiful -- is more of a placeholder.
Personally I like more minimalistic google-style graphics, but all of this
can be tweaked later on.
Content is key I think for now.

**Comment by OndrejMarsalek** [comment]
I noticed the problem with size some time ago but did not have time to dig into it. Unfortunately, it is not possible to get rid of that bulk, wherever it is, without rewriting the history of the repository, which is always dangerous. It will need fixing, though.

**Comment by weifang2321** [comment]
Typo spotted on the about i-pi page:

"If you _fin_ it useful for your research" should be "find" I guess.

**Comment by ceriottm** [comment]
Please feel free to correct this kind of typos and commit directly to
gh-pages.
Thanks
