### ISSUE TITLE
Let's keep the repo clean...

### ISSUE THREAD

**Issue by grhawk** [cosmo-epfl/i-pi-dev#152]
# Branches
## Simply behind master
Since there is nothing to loose deleting them, I would propose to delete them and recreate the useful ones when needed...

- [x] newdep
- [x] constrain
- [x] mts-venkat
- [x] dynma
- [x] style
- [x] script-interface
- [x] forces-copy
- [x] wte
- [x] constraints
- [x] mds

## Easy to merge
(should just be merged, no threats)
- [x] geop

## Easy to merge with small revisions 
(mostly due to the advances on the master)
- [x] newdep-context: improve the readability when defining many dependent quantities.

**Comment by ceriottm** [comment]
Actually this was a useful and important attempt to clean up the depend
mechanism. Basically the idea was that the
whole dset/dget machinery was very cumbersome and one should have a way to
access the depend machinery within the depend object. I think it would be
useful to revive it.

**Comment by grhawk** [comment]
You mean the newdep-context? The newdep should have already been merged...

**Comment by ceriottm** [comment]
Oh. The idea was that we had to "deprecate" the dset/dget route and modify
all of the code.
We can discuss that on Monday

**Comment by ceriottm** [comment]
Time to get rid of some stale branches. Now that we merged in the new depend mechanism, newdep_context can go - I will delete it right now as this is quite a clear-cut case. Other proposals for stale branch removal should be posted here to see if there are objections.

**Comment by ceriottm** [comment]
Also, I would remove bias and all the half-assed REMD branches, unless they contain valuable stuff. 
@grhawk as far as I am concerned they can all go so if no-one objects and you find no leftover pieces of code worth looting, let's wipe 'em all out

**Comment by grhawk** [comment]
Branches mentioned here have been deleted...
