### ISSUE TITLE
fd_epsilon is read from only the last force

### ISSUE THREAD

**Issue by ceriottm** [cosmo-epfl/i-pi-dev#158]
the code picks just the definition of fd_epsilon from the last <force> within <forces>, which makes sense since it's applied at the global <forces> level. However, this is a nightmare because a user won't know unless they read into the code. 
Ideally, fd_epsilon should be an option of <forces>, unless we want to compute sc forces separately from each force evaluator.

**Comment by venkatkapil24** [comment]
So ideally fd_epsilon should be an option of what ? I am guessing the integrator since it is an ingredient of the fourth order integrator.

**Comment by ceriottm** [comment]
No, it is computed by <forces> so it should be an option of <forces>. Now
it is an option of *each* <force> component, but is only applied from the
compound Forces object.

**Comment by venkatkapil24** [comment]
Ah! I see.

**Comment by ceriottm** [comment]
@venkatkapil24 would you care fixing this for good?
