### ISSUE TITLE
Odd behaviour with units

### ISSUE THREAD

**Issue by ollehellman** [cosmo-epfl/i-pi-dev#162]
Hi,

Haven't worked with i-pi in a while, and have gotten started again. I suppose you guys appreciate if I find things as I find odd. Must say I very much appreciate that you can now input the cell as three lattice vectors, makes life so much easier.

Anyway, I naively specified

```
<file mode="xyz">dum.xyz</file>
```

with the header

```
32
# CELL{H}: 8.1000000000 0.0000000000 0.0000000000 0.0000000000 8.1000000000 0.0000000000 0.0000000000 0.0000000000 8.1000000000 cell{angstrom} positions{angstrom}
```

This had the unexpected behavior that the unit is applied twice, so that in the restart file I got a lattice parameter of 28.94 instead of the expected 15.31. This is probably not what was intended.

**Comment by ceriottm** [comment]
Hi Olle, we have changed indeed the behavior of the input parsing so that
in principle you specify the units within the file -- the idea being that
one would like the xyz to be self-explanatory whereas before one always had
to inspect it to know what the units of the cell were.   However, we left
for backwards compatibility the possibility of specifying units in the xml.
What you report here is strange though - was your xml just
<file mode="xyz">dum.xyz</file>
?
I would have expected that behavior if you had specified also
<file mode="xyz" cell_units="angstrom">dum.xyz</file>

Can you attach the xml and xyz input so we can properly debug?

**Comment by ollehellman** [comment]
Ah, my bad. I pasted the wrong input, after I fixed it. It behaves just as you said, if units are specified both in the xml and the xyz, they are applied twice.

```
<simulation>
<output prefix="equil">
    <properties stride='1' filename='out'>[ step, conserved{electronvolt}, temperature{kelvin}, kinetic_md{electronvolt}, kinetic_cv{electronvolt}, potential{electronvolt}]</properties>
</output>
<total_steps>50</total_steps>
<prng><seed>32345</seed></prng>

<ffsocket name="ipisocket" mode="unix">
    <address>ipidriver</address>
</ffsocket>
<system>
<initialize nbeads="4">
    <file mode="xyz" cell_units="angstrom">dum.xyz</file>
    <velocities mode="thermal" units="kelvin"> 300 </velocities>
</initialize>
<forces><force forcefield='ipisocket'></force></forces>
<ensemble>
    <temperature units="kelvin">300</temperature>
</ensemble>
<motion mode='dynamics'>
    <fixcom>True</fixcom>
    <dynamics mode='nvt'>
        <thermostat mode="pile_g">
            <tau units="femtosecond">10</tau>
        </thermostat>
        <timestep units="femtosecond">1</timestep>
    </dynamics>
</motion>
</system>
</simulation>
```
With the xyz file

```
32
# CELL{H}: 8.1000000000 0.0000000000 0.0000000000 0.0000000000 8.1000000000 0.0000000000 0.0000000000 0.0000000000 8.1000000000 cell{angstrom} positions{angstrom}
    Al     0.405000000000E+01 0.405000000000E+01 0.405000000000E+01
    Al     0.202500000000E+01 0.202500000000E+01 0.405000000000E+01
    Al     0.405000000000E+01 0.607500000000E+01 0.202500000000E+01
    Al     0.202500000000E+01 0.405000000000E+01 0.202500000000E+01
    Al     0.202500000000E+01 0.607500000000E+01 0.000000000000E+00
    Al     0.000000000000E+00 0.202500000000E+01 0.607500000000E+01
    Al     0.607500000000E+01 0.000000000000E+00 0.607500000000E+01
    Al     0.000000000000E+00 0.405000000000E+01 0.405000000000E+01
    Al     0.405000000000E+01 0.607500000000E+01 0.607500000000E+01
    Al     0.202500000000E+01 0.405000000000E+01 0.607500000000E+01
    Al     0.202500000000E+01 0.607500000000E+01 0.405000000000E+01
    Al     0.000000000000E+00 0.607500000000E+01 0.607500000000E+01
    Al     0.607500000000E+01 0.405000000000E+01 0.607500000000E+01
    Al     0.405000000000E+01 0.202500000000E+01 0.607500000000E+01
    Al     0.202500000000E+01 0.000000000000E+00 0.607500000000E+01
    Al     0.607500000000E+01 0.607500000000E+01 0.405000000000E+01
    Al     0.202500000000E+01 0.202500000000E+01 0.000000000000E+00
    Al     0.000000000000E+00 0.000000000000E+00 0.405000000000E+01
    Al     0.000000000000E+00 0.202500000000E+01 0.202500000000E+01
    Al     0.607500000000E+01 0.000000000000E+00 0.202500000000E+01
    Al     0.000000000000E+00 0.405000000000E+01 0.000000000000E+00
    Al     0.607500000000E+01 0.202500000000E+01 0.000000000000E+00
    Al     0.405000000000E+01 0.000000000000E+00 0.000000000000E+00
    Al     0.000000000000E+00 0.000000000000E+00 0.000000000000E+00
    Al     0.607500000000E+01 0.202500000000E+01 0.405000000000E+01
    Al     0.405000000000E+01 0.000000000000E+00 0.405000000000E+01
    Al     0.000000000000E+00 0.607500000000E+01 0.202500000000E+01
    Al     0.607500000000E+01 0.405000000000E+01 0.202500000000E+01
    Al     0.405000000000E+01 0.202500000000E+01 0.202500000000E+01
    Al     0.202500000000E+01 0.000000000000E+00 0.202500000000E+01
    Al     0.607500000000E+01 0.607500000000E+01 0.000000000000E+00
    Al     0.405000000000E+01 0.405000000000E+01 0.000000000000E+00
```

**Comment by ceriottm** [comment]
OK. Then, for good or for bad, this is the current expected behavior. The idea was pushing outwards the point at which units conversion is made, but we are a bit wary of enforcing yet another non-standard "decorated xyz" format. I'd be glad to have a discussion on what you see as the most appropriate/logical behavior.  @grhawk and @ipoltavskyi  can also chime in as they did most of the implementation of this in-file units specification.

**Comment by ollehellman** [comment]
Units are the worst invention in the world, all categories, and there is no way of doing it that will not make your head hurt.

I found another behaviour I found odd, but perhaps is expected as well:

```
<trajectory stride='1' filename='positions' cell_units='angstrom'>
    positions{angstrom}
</trajectory>
```

Applies the unit twice, whereas 

```
<trajectory stride='1' filename='positions' cell_units='angstrom'>
    positions
</trajectory>
```

Produces the output that I would expect, lattice vectors in Å, and positions in Å. Not sure if that was what was intended.

If my personal opinion matters, I would prefer output to have the cell defined as three lattice vectors, and positions in fractional coordinates. abcABC-format is a little annoying, since there is no unique way of transforming that to latticevectors (at least not a unique way that everyone agrees on). In addition, if everything could be lumped in a hdf5-file, that would make life so much easier -- one file per simulation, and the format is self-documenting, trivial to parse, takes very little space and in general wonderful to work with compared to plain text files. I get that the xml-files more or less have this information, but parsing xml in something not python is ... not fun.

**Comment by ceriottm** [comment]
OK, what you found on the output side is definitely a bug. cell_units only
specify the units for the cell parameters, and should not affect positions.
@grhawk, could you look into this and fix it?

**Comment by ceriottm** [comment]
More generally,
* we leave all options for cell specification, but internally the vectors
are oriented in such a way that abcABC is univocal. scaled coordinates are
a terrible idea when you work on anything that is not solid-state, people
doing bio stuff would hate us. I think that the fact you *can* specify the
cell as the lattice vectors, and that then it rotates the thing in the
internal format
* a binary I/O is on the todo list - if you feel like contributing, this
would be a great infrastructural addition.

**Comment by grhawk** [comment]
Hi,

@ollehellman thank you for reporting strange behaviors. This is very useful to debug the code. For the specific case, anyway, I am not able to reproduce the bug with some similar example. Could you please send me all your files (ipi and lammps input with respective initialization files)?

**Comment by ceriottm** [comment]
Is this issue resolved? Riccardo, I had the impression that basically we could just be a bit more verbose when parsing the input. Is that implemented, and does that clarify what was Olle's problem?

**Comment by grhawk** [comment]
@ceriottm @mahrossi 
I think this [commit](https://github.com/cosmo-epfl/i-pi-dev/commit/f069359a5e24bcdb8aaec6165e21bf309898bd2f) should definitely solve the problem! 

Waiting for comments!
