### ISSUE TITLE
Bug in quantum kinetic energy

### ISSUE THREAD

**Issue by litman90** [cosmo-epfl/i-pi-dev#169]
In line 707 of  i-pi-dev/ipi/engine/properties.py the virial kinetic energy estimator doesn't take account that the number of degrees of freedom could be different that 3*natoms. (For example,  when center of mass or atoms are fixed ). There is a similar problem in the quantum kinetic energy tensor estimator.

**Comment by ceriottm** [comment]
Discussing this with Mariana right now. It is not really a bug, more an
arbitrary choice.
Depends on whether you consider the fixed atoms as a model for
infinitely-restrained
atoms, or as an external buffer layer.

**Comment by ipoltavskyi** [comment]
Hi,

This is a good opportunity to ask about another related thing which is useful to have in i-Pi but which is, as far as I know, not there yet.
Can we make an option to fix positions of centroids for some particles? For instance this is important for thermodynamic integration. Is it in TODO list or future plans?

Best regards
Igor

**Comment by ceriottm** [comment]
Hi Igor,
 it's not completely trivial to do, but in principle it is feasible. I'd
say the easiest would be done as an option to fixatoms.
you specify how many NM you want to block, with the default being all of
them.

**Comment by mahrossi** [comment]
I think we decided to make the classical kinetic energy output in the presence of fixed atoms consistent with the definition of the kinetic_cv (add kTs). Assigning myself to the task.

**Comment by ceriottm** [comment]
So how are we doing on this?

**Comment by mahrossi** [comment]
Should I just change the default for the classical kinetic energy for
constrained atoms?

**Comment by ceriottm** [comment]
yes, I think it works to have a fictitious KE assigned to the fixed degrees
of freedom.
michele

**Comment by mahrossi** [comment]
Finally doing this in ke-fix branch. Still had no time to test -- slightly tricky due to all the options and the definition of temperature. Will test later.

**Comment by venkatkapil24** [comment]
@mahrossi  @litman90 : I was wondering if this has been fixed.

**Comment by mahrossi** [comment]
Hi Venkat, my understanding is that this was solved when we merged the way
we distribute the classical kinetic energy through the degrees of freedom
in the other commit last week.

**Comment by venkatkapil24** [comment]
I am not 100 % sure since get_kincv() doesn't call get_temp or get_kinmd().

**Comment by mahrossi** [comment]
Right, but the problem was just an inconsistency between the way get_kincv
was handling the fixed degrees of freedom and the way get_kinmd() was
handling them.
In the thread here above we decided to change only the way get_kinmd() was
handling it, which it seems has been done in the last commit.
