### ISSUE TITLE
Restarting from checkpoint skip a step

### ISSUE THREAD

**Issue by grhawk** [cosmo-epfl/i-pi-dev#177]
When restarting from checkpoint it looks like a step is skipped. 
![image](https://cloud.githubusercontent.com/assets/7868446/24971309/d5cacb38-1fb7-11e7-8e59-c2ac988ac123.png)
![image](https://cloud.githubusercontent.com/assets/7868446/24971324/e017ed50-1fb7-11e7-8b6e-edb95bfbb916.png)

These are two example of the same system using two different checkpoints. The green line is obtained with a single run while the red is obtained stopping and restarting from a checkpoint. 

Attached also the input. The command used to run the driver is written inside the xml file.

[test-restart-master-reference.tar.gz](https://github.com/cosmo-epfl/i-pi-dev/files/917413/test-restart-master-reference.tar.gz)

**Comment by ceriottm** [comment]
Is this only with REMD or in general?

**Comment by grhawk** [comment]
It is general... Only the names are strange but the attached example is a simple md

**Comment by ceriottm** [comment]
This is not restarting from RESTART, right? this is using a checkpoint as a
restart.
Might just need to take one off (or add one) the step counter when saving
checkpoints are saved.

**Comment by grhawk** [comment]
Yes... this is a checkpoint... I can try this solution.

**Comment by ceriottm** [comment]
Any progress on this? Seems an easy bug to hunt down and fix

**Comment by ceriottm** [comment]
@grhawk could we solve and close this please?

**Comment by ceriottm** [comment]
OK think this has been fixed now
