### ISSUE TITLE
Getting weird error when trying to print out trajectory

### ISSUE THREAD

**Issue by kuenzeln** [cosmo-epfl/i-pi-dev#199]
Hey,

as already discussed in the forum I have the error in the i-pi-dev/master branch that when
<trajectory filename='mom.out' stride='1' format='xyz' cell_units='angstrom'> momenta </trajectory>
or <trajectory filename='mom.out' stride='1' format='xyz' cell_units='angstrom'> momenta{} </trajectory>
or <trajectory filename='mom.out' stride='1' format='xyz' cell_units='angstrom'> momenta{atomic_unit} </trajectory>
is defined the program crashes. But not while reading the xml file but first when one tries to connect the driver.
You can try that in the examples/harmonic/ folder. The following input was used.
[input.xml.zip](https://github.com/cosmo-epfl/i-pi-dev/files/1260688/input.xml.zip)

The error which is shown is:

Traceback (most recent call last):
  File "/data/nk158/i-pi-dev-master/bin/i-pi", line 101, in <module>
    main(args[0], options.do_yappi)
  File "/data/nk158/i-pi-dev-master/bin/i-pi", line 51, in main
    simulation.run()
  File "/cluster/data/nk158/i-pi-dev-master/ipi/engine/simulation.py", line 220, in run
    o.write()  # threaded output seems to cause random hang-ups. should make things properly thread-safe
  File "/cluster/data/nk158/i-pi-dev-master/ipi/engine/outputs.py", line 318, in write
    self.system.trajs.print_traj(self.what, self.out, b=0, format=self.format, cell_units=self.cell_units, flush=doflush)
  File "/cluster/data/nk158/i-pi-dev-master/ipi/engine/properties.py", line 2297, in print_traj
    fatom.q = cq
  File "/cluster/data/nk158/i-pi-dev-master/ipi/utils/depend.py", line 802, in __setattr__
    return obj.__set__(self, value)
  File "/cluster/data/nk158/i-pi-dev-master/ipi/utils/depend.py", line 614, in __set__
    self.__setitem__(slice(None, None), value=value)
  File "/cluster/data/nk158/i-pi-dev-master/ipi/utils/depend.py", line 590, in __setitem__
    self.view(np.ndarray)[index] = value
ValueError: could not broadcast input array from shape (4,3) into shape (3)

**Comment by venkatkapil24** [comment]
can you git pull on master and try again ?

**Comment by kuenzeln** [comment]
Works now but it just prints one file even though I didn't write a certain bead number. Shouldn't it then print the momenta for each bead in a different file?

**Comment by venkatkapil24** [comment]
can you try the fix-traj branch ?

**Comment by kuenzeln** [comment]
Works well with that change now. Thanks a lot!

**Comment by venkatkapil24** [comment]
If you can confirm that everything is in order then we can proceed to merge this one and close the issue.

**Comment by kuenzeln** [comment]
Guess so. With the change in engine/properties.py and engine/outputs.py everything works fine for me now.
