### ISSUE TITLE
Quantum espresso fails in the qespresso/li4 example.

### ISSUE THREAD

**Issue by pjuda** [cosmo-epfl/i-pi-dev#211]
The quantum espresso example with lithium does not work (examples/qespresso/li4).
Quantum espresso throws the following error and stops:
`     Error in routine davcio (10):
     unit is not opened
`

**Comment by ceriottm** [comment]
Any progress here? QE is one of the core codes for i-PI and I'd like to make sure it works as reliably as possible. Not having the possibility of using k-points is a big issue

**Comment by pjuda** [comment]
I'll summarize the problem here for future reference.
We found that QE driver fails (pw run_driver.f90, run_driver()) when multiple k-points are chosen. This happens when the driver tries to reset the history of potential and wavefunction, which are extrapolated and used to improved initial guess for next calculation step. Most probably, the point to intervene is around the line 186  in run_driver.f90 - driver does something wrong when resetting the history and more k-points than only gamma are used.

There are two tasks related to the issue:
1. We should obey the extrapolate options from &IONS (so that one can switch off the extrapolation)
2. Fix the actual bug, so understand how to handle properly history reset in pw driver

Regarding 1.
If 'scf' option of calculation is chosen, the namespace &IONS is ignored. The extrapolation which pw driver uses is hardcoded and set to default to second order. How should I proceed with the change, so that this extrapolate option is taken into account? Where should it be given as the parameter? There are two cards: wfc_extrapolation and pot_extrapolation.

Regarding 2.
I will report as soon as I have something.

**Comment by pjuda** [comment]
I found a solution which fixes the bug. Files should not be closed; instead, we need to delete the files that hold the history and also wipe the update file.

The cleanest way to obey the extrapolation options in &IONS, would be to introduce a check in the `Modules/read_namelists.f90` if the program is run in i-pi mode. This can be achieved by means of a function `is_run_in_ipi_driver_mode` and `USE command_line_options, ONLY: command_line`. Since it interferes with q-e architecture, can we do such a change? Should the function `is_run_in_ipi_driver_mode` be introduced directly in the `Modules/read_namelists.f90`, in `PW/run_driver.f90` or in a separate module?

**Comment by ceriottm** [comment]
thanks! please come up with a patch that is as clean as possible in your
own view, then we'll negotiate with the QE developers if it's clean enough
or there is a better way
but it's better to start from something that works already...

**Comment by pjuda** [comment]
I attach the proposed patch below.
I tested it using:
- i-pi regtests,
- checked that example works,
- q-e regtests (pw-serial, cp-serial, pw-parallel, cp-parallel)

[i-pi-issue-211-patch.txt](https://github.com/cosmo-epfl/i-pi-dev/files/1539920/i-pi-issue-211-patch.txt)

**Comment by ceriottm** [comment]
so now this respects the extrapolation options in &IONS ? I'll try to test this on the plane if I manage to download the latest snapshot of QE

**Comment by pjuda** [comment]
Yes, both issues are fixed now.
My initial patch applied to official github version of q-e: [https://github.com/QEF/q-e](url) and to the commit: `master: b165147 Debug IFC reading in the case of ibrav==0`
Paolo Gianozzi reviewed the patch, improved it and pushed to the official QE git: 
[diffs.txt](https://github.com/cosmo-epfl/i-pi-dev/files/1547381/diffs.txt)

Finally, I reran i-PI regtest and lithium example with the updated version of the QE code using the following commit of QE: `4dbab2d37649578a96fbc243caccf9a0c796c9f6`
