### ISSUE TITLE
Alchemical example lammps/h2o-alchemical fails regression test

### ISSUE THREAD

**Issue by pjuda** [cosmo-epfl/i-pi-dev#212]
To reproduce the issue, checkout fix-examples branch, go to examples/regtest/lammps and execute regtest to create a reference run:
`../../../tools/py/regtest.py --create-reference --tests-folder . --folder-run run`

Next, run the regtest:
`../../../tools/py/regtest.py --tests-folder . --folder-run run`

You will notice that h2o-alchemical fails the regtest. Is it expected behaviour due to the fact that Monte Carlo procedure uses a different seed for each run?

**Comment by ceriottm** [comment]
might be or might not. if the execution is not threaded then the MC should pick from the same PRNG stream as everyhting else and so results with the same seed should be reproducible.

**Comment by ceriottm** [comment]
Fixed. Was using wrong PRNG source.
