### ISSUE TITLE
the directory io inside utils/ is named after a standard python module

### ISSUE THREAD

**Issue by venkatkapil24** [cosmo-epfl/i-pi-dev#215]
Saw this while working on the automatic pep indentation. The application fails when you launch it in this directory. It is unable to import the standard io module [https://docs.python.org/2/library/io.html]  because a directory called io already exists. I think that we should rename ipi.utils.io to something else like ioinfra or something else.

**Comment by ceriottm** [comment]
pepper script works, branch has been merged and deleted, and I'll also close this issue.
