### ISSUE TITLE
Apply a force based on positions of all beads

### ISSUE THREAD

**Issue by kzinovjev** [cosmo-epfl/i-pi-dev#227]
Hi all,
I am working on a method that applies a biasing force to the beads depending on the coordinates of the entire ring-polymer. For a simple example, lets say I want to apply a harmonic restraint to a bead-average value of some interatomic angle. So, it can't be done in the force driver, since drivers only "see" one bead at a time. 
I have solved this issue in cp2k by writing a custom i-pi driver that "tricks" i-pi into seeing one cp2k instance as N ones, N being the number of beads. That way I can get all the beads from i-pi in a single cp2k process, calculate the required forces and send them back to i-pi. But this approach obviously does not scale well, since I have to calculate forces for N beads in a single driver.
It would make much more sense to provide a "custom" force component to i-pi itself.

Could somebody indicate a way to go to have this implemented? E.g. a clue on how to get the bead positions, add an extra force and a place in the code where it is safe to do so. I have zero familiarity with the i-pi source code, so any help will be really appreciated.

Thanks in advance!

P.S. Being able to apply an external RP-dependent force would also allow to perform centroid Umbrella Sampling simulations along an arbitrary coordinate, so this feature might be also interesting for a wider audience.

**Comment by ceriottm** [comment]
If all you need is to add a force that depends on the centroid, you can do
this very easily by using a contraction, that is you specify something like
<force nbeads="1" forcefield="ffname"/>
If you need something dependent on many beads I agree this is not
implemented, and it would be very hard to do it without changing in depth
how the force evaluation machinery is built.

**Comment by kzinovjev** [comment]
I need to apply a bias to an average of a non-linear function of bead coordinates, like the angle example I mentioned. So, I need `V(<f(x)>)`, not `V(f(<x>))` which would indeed be just a force on the centroid.
I do not aim for an elegant solution at the moment, just need something that will work. For example, would messing with the forces in `Dynamics.step()` be ok? Like:
```
def step(self, step=None):
    add_some_force(self.beads.q, self.forces.f) #self.forces.f is changed here
    self.integrator.step(step)
```

**Comment by ceriottm** [comment]
Yes, I suggest you create your own Motion class that does this. It's
probably the best place to intervene without having to comprehend the
intricacies of the ForceField / Forces implementation.
However you cannot modify the forces in the way you propose. Forces are
depend objects that get computed automatically, you cannot modify them. You
should basically have your own integrator that replicates
one of the simple VV integrators and do e.g.

self.beads.p += self.forces.f * self.dt/2
self.beads.p += my_fancy_force(self.beads.q) * self.dt/2
.....

M

**Comment by kzinovjev** [comment]
Great, seems easy. Thank you!
