### ISSUE TITLE
Read also title/comment from trajectory files

### ISSUE THREAD

**Issue by OndrejMarsalek** [cosmo-epfl/i-pi-dev#90]
I would like to add the title/comment read from trajectory files to the dictionary that is returned by the I/O functions `read_*`. This is useful if you want to preserve that information when writing the processed frames again.

**Comment by venkatkapil24** [comment]
@OndrejMarsalek : I think this is now resolved, right ?

**Comment by OndrejMarsalek** [comment]
Yeah, I think it's now irrelevant, as there have been extensive changes to I/O independent of this.
