### ISSUE TITLE
Append to output only on restart

### ISSUE THREAD

**Issue by OndrejMarsalek** [cosmo-epfl/i-pi-dev#92]
As discussed in #91, we should append to output files only if it is a restarted simulation, otherwise we should write new files (while keeping backups if they already exist). If the file to be appended to does not happen to exist, append behaves as write, so no harm.

Do this be adding a flag to `Simulation` (defaulting to `False`), which indicates whether this is a restarted simulation. This can then be set to `True` before a restart file is written. I think it should be kept as `False` for regular checkpoints written by the output mechanism - they are probably meant for new simulations and if they append to any existing files, there will likely be duplicate frames.

**Comment by venkatkapil24** [comment]
Can it be closed ?
